### ISSUE TITLE
ActiveMQ error message at shutdown

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#118]
Reported error

ERROR [pool-9-thread-1] - ID:mauro-9326-1425838119102-4:1:8:1 failed to delivered acknowledgements
javax.jms.JMSException: Transport disposed.
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
        at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1320)
        at org.apache.activemq.ActiveMQConnection.asyncSendPacket(ActiveMQConnection.java:1312)
        at org.apache.activemq.ActiveMQSession.asyncSendPacket(ActiveMQSession.java:1914)
        at org.apache.activemq.ActiveMQSession.sendAck(ActiveMQSession.java:2080
)
        at org.apache.activemq.ActiveMQMessageConsumer$4.run(ActiveMQMessageConsumer.java:764)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Transport disposed.
        at org.apache.activemq.transport.vm.VMTransport.oneway(VMTransport.java:79)
        at org.apache.activemq.transport.MutexTransport.oneway(MutexTransport.java:68)
        at org.apache.activemq.transport.ResponseCorrelator.oneway(ResponseCorrelator.java:60)
        at org.apache.activemq.ActiveMQConnection.doAsyncSendPacket(ActiveMQConnection.java:1318)
        ... 9 more
INFO  [ActiveMQ ShutdownHook] - Apache ActiveMQ 5.9.0 (9a370747-f3aa-4503-a215-7
94c6a7a6774, ID:mauro-9326-1425838119102-0:2) uptime 49.016 seconds
INFO  [ActiveMQ ShutdownHook] - Apache ActiveMQ 5.9.0 (9a370747-f3aa-4503-a215-7
94c6a7a6774, ID:mauro-9326-1425838119102-0:2) is shutdown

**Comment by dmitraver** [comment]
Hi!

I would like to pick this one.

**Comment by mcicolella** [comment]
@dmitraver Ok, thanks!
