### ISSUE TITLE
Notify the user when Freedomotic can't load

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#126]
If there is any problem on the loading of FD (due for a bad configured environment), FD shuts down without notifing the user, so the user just think that FD doesn't work.
We need to offer the info to the user in a nice way

**Comment by mcicolella** [comment]
@P3trur0 what do you think?

**Comment by P3trur0** [comment]
@mcicolella this seems a little abstract scenario. What do you specifically mean with startup problem? The front end part or the engine itself?

One proposal could be to send either an e-mail or to display a basic GUI prompt.

However, we should evaluate how much each of those approaches could be feasible according to the failure scenario (e.g.: if the JVM goes down it'd be difficult to perform any notification from freedomotic itself).

**Comment by mcicolella** [comment]
@P3trur0 
I agree with you. If you start Freedomotic manually from command line you can see any log message about startup problems: environment file not found, network not available, other missing files etc
But an unmanned/headless installation requires a notification system. The same if you start FD by .exe or .sh file: the spash screen disappears and you don't know what happened.

**Comment by mcicolella** [comment]
Another notification: when the network is not available (e.g. PC not connected to a LAN/WLAN) FD stops with a lot of error messages

`ERROR [main] - Failed to start Apache ActiveMQ ([ba0cb4d7-8aa8-4ad6-8241-7264de82a50f, ID:emmecilab-42086-1486394041702-0:2], java.net.SocketException: bad argument for IP_MULTICAST_IF2)
INFO  [main] - Apache ActiveMQ 5.14.1 (ba0cb4d7-8aa8-4ad6-8241-7264de82a50f, ID:emmecilab-42086-1486394041702-0:2) is shutting down
INFO  [main] - Network Connector DiscoveryNetworkConnector:NC:BrokerService[ba0cb4d7-8aa8-4ad6-8241-7264de82a50f] stopped
ERROR [main] - Failed to advertise our service: freedomotic-commander.ActiveMQ-4.dead.%localhost%tcp://emmecilab:41678
java.io.IOException: Network is unreachable
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at org.apache.activemq.transport.discovery.multicast.MulticastDiscoveryAgent.doAdvertizeSelf(MulticastDiscoveryAgent.java:446)
`

**Comment by amenak77** [comment]
Maybe the nicest way to notify the user about Freedomotic startup failure is an alert icon in the traybar. It is a quite universal GUI element whatever OS you are using. If you can add a baloon with critical last ActiveMQ warnings too, perhaps it would be perfect ;)
