### ISSUE TITLE
Telegram-bot plugin not working with last dailybuilds

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#268]
The following exception is raised at startup

`Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.SerializationConfig
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
	at org.telegram.telegrambots.bots.DefaultAbsSender.<init>(DefaultAbsSender.java:54)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:35)
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.<init>(TelegramLongPollingBot.java:31)
	at com.freedomotic.plugins.devices.telegrambot.FreedomoticBotHandlers.<init>(FreedomoticBotHandlers.java:87)
	at com.freedomotic.plugins.devices.telegrambot.TelegramBot.onStart(TelegramBot.java:78)
	at com.freedomotic.api.Protocol$1.run(Protocol.java:138)
	at org.apache.shiro.subject.support.SubjectRunnable.doRun(SubjectRunnable.java:120)
	at org.apache.shiro.subject.support.SubjectRunnable.run(SubjectRunnable.java:108)
	at com.freedomotic.api.Protocol.start(Protocol.java:156)
	at com.freedomotic.app.Freedomotic.start(Freedomotic.java:307)
	at com.freedomotic.app.Freedomotic.main(Freedomotic.java:439)
`

Maybe a lib version conflict.

**Comment by mcicolella** [comment]
It seems related only to Linux 64 bit platforms. On Windows 8.1 64 bit it works well.
In each case I'm using Oracle Java 1.8.
@P3trur0 any idea?

**Comment by P3trur0** [comment]
@mcicolella are the library dependencies properly provided? Which Jackson version has being used?

**Comment by mcicolella** [comment]
Yes. The libraries are dependencies of 
<dependency>
            <groupId>org.telegram</groupId>
            <artifactId>telegrambots</artifactId>
            <version>2.4.4.5</version>
</dependency>
The strangeness is that the same plugin works on Win and not on Linux. I haven't a Mac to make some tests and maybe I should try on a Linux 32 bit.

**Comment by P3trur0** [comment]
@mcicolella I have the same problem on a Linux 32bit VM. I'll give a look right now.

**Comment by P3trur0** [comment]
PR opened. See #269.
