### ISSUE TITLE
Harvester plugin not working

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#272]
The Harvester plugin doesn't work correctly and the plugin description reports "Starting ..." instead of "Connected to database".
I tested it on Linux Ubuntu 64 bit.

1. You need to add `-XX:+AlwaysLockClassLoader` to VM options to workaround a known issue with OpenJPA and ClassLoader. 
Without this the following exception is raised
`414  UsageData  INFO   [main] openjpa.Runtime - Starting OpenJPA 2.3.0
Exception in thread "main" java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/apache/openjpa/jdbc/identifier/DBIdentifier$DBIdentifierType"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
`
2. At startup the plugin reports only warnings but doesn't load correctly
`17  UsageData  WARN   [main] openjpa.Runtime - The persistence unit "UsageData" was found multiple times in the following resources "[jar:file:/home/emmecilab/Scrivania/214/lib/freedomotic-model-5.6-SNAPSHOT.jar!/META-INF/persistence.xml, jar:file:/home/emmecilab/Scrivania/214/plugins/providers/freedomotic-drupal-marketplace-3.0-jar-with-dependencies.jar!/META-INF/persistence.xml]", but persistence unit names should be unique. The first persistence unit matching the provided name in "jar:file:/home/emmecilab/Scrivania/214/lib/freedomotic-model-5.6-SNAPSHOT.jar!/META-INF/persistence.xml" is being used.
96  UsageData  INFO   [main] openjpa.Enhance - You have enabled runtime enhancement, but have not specified the set of persistent classes.  OpenJPA must look for metadata for every loaded class, which might increase class load times significantly.
399  UsageData  INFO   [main] openjpa.Runtime - OpenJPA dynamically loaded the class enhancer. Any classes that were not enhanced at build time will be enhanced when they are loaded by the JVM.
432  UsageData  INFO   [main] openjpa.Runtime - Starting OpenJPA 2.3.0
1171  UsageData  WARN   [main] openjpa.Enhance - Unenhanced classes were detected even though the enhancer has ran. Ensure that the EntityManagerFactory is created prior to creating any Entities.    
2017-07-17 10:35:24,659 WARN  [main] - ArgumentException This configuration disallows runtime optimization, but the following listed types were not enhanced at build time or at class load time with a javaagent: "
com.freedomotic.model.charting.UsageData".
`

**Comment by mcicolella** [comment]
Just find another problem. When you add the option `-XX:+AlwaysLockClassLoader` the freedomotic-markeplace plugin throws the following exception
`Cannot create class com.freedomotic.marketplace.FreedomoticMarketPlace

java.lang.LinkageError: loader (instance of  sun/misc/Launcher$ExtClassLoader): attempted  duplicate class definition for name: "sun/security/ec/ECDSASignature$SHA1"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.security.Provider$Service.getImplClass(Provider.java:1636)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at java.security.Signature.isSpi(Signature.java:292)
	at java.security.Signature.getInstance(Signature.java:236)
	at sun.security.ssl.JsseJce.getSignature(JsseJce.java:225)
	at sun.security.ssl.JsseJce$EcAvailability.<clinit>(JsseJce.java:416)
	at sun.security.ssl.JsseJce.isEcAvailable(JsseJce.java:194)
	at sun.security.ssl.CipherSuite$KeyExchange.isAvailable(CipherSuite.java:371)
	at sun.security.ssl.CipherSuite.isAvailable(CipherSuite.java:185)
	at sun.security.ssl.SSLContextImpl.getApplicableCipherSuiteList(SSLContextImpl.java:303)
	at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:41)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:424)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1634)
	at java.security.Provider$Service.newInstance(Provider.java:1592)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at org.restlet.ext.ssl.DefaultSslContextFactory.createSslContext(DefaultSslContextFactory.java:363)
	at org.restlet.ext.httpclient.HttpClientHelper.configure(HttpClientHelper.java:274)
	at org.restlet.ext.httpclient.HttpClientHelper.start(HttpClientHelper.java:478)
	at org.restlet.Client.start(Client.java:217)
	at org.restlet.routing.Filter.start(Filter.java:274)
	at org.restlet.Restlet.handle(Restlet.java:315)
	at org.restlet.routing.Filter.handle(Filter.java:202)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1136)
	at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1225)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1068)
	at org.restlet.resource.ClientResource.handle(ClientResource.java:1044)
	at org.restlet.resource.ClientResource.post(ClientResource.java:1453)
	at com.freedomotic.marketplace.postplugin.JavaUploader.postTaxonomyGetTree(JavaUploader.java:140)
	at com.freedomotic.marketplace.util.DrupalRestHelper.retrieveCategories(DrupalRestHelper.java:106)
	at com.freedomotic.marketplace.FreedomoticMarketPlace.updateCategoryList(FreedomoticMarketPlace.java:74)
	at com.freedomotic.marketplace.FreedomoticMarketPlace.<init>(FreedomoticMarketPlace.java:45)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.openide.util.lookup.implspi.SharedClassObjectBridge.newInstance(SharedClassObjectBridge.java:64)
	at org.openide.util.lookup.MetaInfServicesLookup$P.getInstance(MetaInfServicesLookup.java:492)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1044)
	at org.openide.util.lookup.AbstractLookup$R.allInstances(AbstractLookup.java:1024)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeSingleResult(ProxyLookup.java:1267)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.computeDelegate(ProxyLookup.java:1105)
	at org.openide.util.lookup.ProxyLookup$LazyCollection.access$900(ProxyLookup.java:1033)
	at org.openide.util.lookup.ProxyLookup$LazyCollection$1.hasNext(ProxyLookup.java:1233)
	at com.freedomotic.marketplace.MarketPlaceService.getCategoryList(MarketPlaceService.java:130)
	at com.freedomotic.jfrontend.MarketPlaceForm$1$1.run(MarketPlaceForm.java:88)
	at java.lang.Thread.run(Thread.java:748)
`
All is OK when you use the same option without the harvester plugin.

**Comment by mcicolella** [comment]
#273

**Comment by amenak77** [comment]
This could be useful.  http://users.openjpa.apache.narkive.com/YhxFD2bS/jdk-1-7-seems-to-be-causing-an-issue-with-latest-snapshot
