### ISSUE TITLE
MainWindow class throws a NPE exception

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/freedomotic#355]
The following exception is raised at startup by [MainWindow.java](https://github.com/freedomotic/freedomotic/blob/master/plugins/devices/frontend-java/src/main/java/com/freedomotic/jfrontend/MainWindow.java) class

`
2017-10-09 17:14:00,322 ERROR [AWT-EventQueue-0] - Error setting Map title java.lang.NullPointerException
	at com.freedomotic.jfrontend.MainWindow.setMapTitle(MainWindow.java:453)
	at com.freedomotic.jfrontend.MainWindow.initializeRenderer(MainWindow.java:428)
	at com.freedomotic.jfrontend.MainWindow.setWindowedMode(MainWindow.java:260)
	at com.freedomotic.jfrontend.MainWindow.<init>(MainWindow.java:120)
	at com.freedomotic.jfrontend.JavaDesktopFrontend.createMainWindow(JavaDesktopFrontend.java:114)
	at com.freedomotic.jfrontend.utils.SplashLogin.btnLoginActionPerformed(SplashLogin.java:208)
	at com.freedomotic.jfrontend.utils.SplashLogin.access$000(SplashLogin.java:34)
	at com.freedomotic.jfrontend.utils.SplashLogin$1.actionPerformed(SplashLogin.java:118)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

`

**Comment by sebast26** [comment]
I looked into this and I see two ways of handling this issue:

1. remove IMHO unnecessary invocations of ```setMapTitle``` in ```setWindowedMode()``` and ```initializeRenderer()``` methods OR
2. add checking if ```drawer != null``` in ```setMapTitle``` method

Of course I could be mistaken and in some cases 1. approach could be wrong (for some reason setting map title with empty or notinited_inited string is desirable). Please correct me if I am wrong because from what I can see now there are always 3 invocations of ```setMapTitle``` method and only the last one is sensible.

Which way you want to go with fixing this?

**Comment by mcicolella** [comment]
@P3trur0 what do you think?

**Comment by P3trur0** [comment]
@sebast26 @mcicolella maybe I'd go with option 2.

**Comment by sebast26** [comment]
@P3trur0 @mcicolella Yeah, it's the safest one. I've added a pull request.
